

var date=new Date()
console.log(date.toString())
// console.log(date.toLocaleDateString())
// console.log(date.toLocaleTimeString())
/*console.log(date.getDate())
console.log(date.getFullYear())
console.log(date.getMonth())
console.log(date.getDay())
console.log(date.getDate)
console.log(date.getHours())
console.log(date.getMinutes())
console.log(date.getSeconds())
console.log(date.getMilliseconds())*/


// var date=new Date(2026,1,12,7,24,34)
// console.log(date.toString())
// console.log(date.getFullYear())
// console.log(date.getMonth())
// console.log(date.getDate())
// console.log(date.getDay())
// console.log(date.getHours())
// console.log(date.getMinutes())
// console.log(date.getSeconds())
// console.log(date.getMilliseconds())
// console.log(date.toLocaleTimeString())
// date.getTime()
// console.log(date.toLocaleTimeString())
// console.log(date.getTime())


// date.setFullYear(2029)
// console.log(date.toString())
// date.setMonth(0)
// console.log(date.toString())
// date.setHours(10)
// console.log(date.toString())
// date.setMinutes(30)
// console.log(date.toString())
// date.setSeconds(45)
// console.log(date.toString())
// date.setMilliseconds(699)
// console.log(date)
// date.setTime(8)
// console.log(date.toString())
